version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage_plugin_app
    ports:
      - "5432:5432"
    networks:
      - backstage-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backstage:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage_plugin_app
    ports:
      - "7007:7007"
    depends_on:
      - postgres
    networks:
      - backstage-network

volumes:
  postgres-data:
    driver: local


networks:
  backstage-network:
    driver: bridge
